import assert from 'node:assert/strict';
import { verifyMarketPages } from './market-pages.mjs';
import { verifySettingsPages } from './settings-pages.mjs';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
// The repository's existing browser test dependency; no browser download needed.
const { chromium } = createRequire(resolve(root, 'apps/electron/package.json'))('playwright-core');
const origin = new URL(process.env.FELIX_TEST_URL ?? 'http://127.0.0.1:8787').origin;
const artifacts = resolve(root, 'artifacts/web');
await mkdir(artifacts, { recursive: true });
const browser = await chromium.launch({ headless: true,
  executablePath: process.env.FELIX_BROWSER_PATH ?? (process.platform === 'win32'
    ? 'C:/Program Files/Google/Chrome/Application/chrome.exe' : '/usr/bin/google-chrome'),
});
// Bound test polling so assertions do not consume the application's request budget.
const waitForState = (target, fn, arg, options = {}) => target.waitForFunction(fn, arg, { polling: 100, ...options });
const errors = [], steps = [], requestCounts = {};
let page;
try {
  steps.push(await verifyMarketPages(browser, origin, artifacts));
  steps.push(await verifySettingsPages(browser, origin, artifacts));
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.route('**/*', (route) => route.request().url().startsWith(origin + '/') ? route.continue() : route.abort());
  page = await context.newPage(); page.on('request', (request) => { if (request.url().endsWith('/api/rpc')) { const method = request.postDataJSON()?.method; requestCounts[method] = (requestCounts[method] ?? 0) + 1; } }); page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(origin, { waitUntil: 'domcontentloaded' });
  await page.getByTestId('sidebar').waitFor();
  assert.match(await page.locator('body').innerText(), /示例行情/);
  assert.equal(await page.evaluate(() => Boolean(window.electronAPI)), false);
  await page.getByTestId('market-dashboard').waitFor();
  const getWatchlist = () => page.evaluate(async () => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"workspace.get"}' })).json()).data.watchlist);
  const originalWatchlist = await getWatchlist();
  await page.getByTestId('assistant-close').click();
  for (const [code, first, second] of [['CN', '000001.SH', '399001.SZ'], ['HK', 'HSI.HK', 'HSTECH.HK'], ['US', 'SPX.US', 'NDX.US']]) {
    await page.getByRole('tab', { name: code === 'CN' ? 'A 股（CN）' : code === 'HK' ? '港股（HK）' : '美股（US）', exact: true }).click();
    await page.locator('.felix-index-card').first().getByRole('button').click();
    await page.locator(`[data-testid=index-workspace][data-symbol="${first}"]`).waitFor();
    await page.getByTestId('chart-canvas').waitFor();
    await page.getByText(/^暂无可核验的指数分时数据/).waitFor();
    await page.getByTestId(`index-item-${second}`).click();
    await page.locator(`[data-testid=index-workspace][data-symbol="${second}"]`).waitFor();
    await page.getByTestId('chart-canvas').waitFor();
    assert.equal(await page.getByTestId('workspace-home').count(), 0, 'index selection opens its own page');
    assert.deepEqual(await getWatchlist(), originalWatchlist, 'index browsing does not alter watchlists');
    assert.doesNotMatch(await page.locator('.felix-indices-price strong').innerText(), /[$¥]/, 'index levels use points instead of stock currencies');
    await page.screenshot({ path: resolve(artifacts, `indices-${code}.png`) });
    if (code === 'CN') {
      await page.getByRole('button', { name: '切换深色主题（Dark theme）', exact: true }).click();
      await page.waitForTimeout(200);
      await page.screenshot({ path: resolve(artifacts, 'indices-CN-dark.png') });
      await page.getByRole('button', { name: '切换浅色主题（Light theme）', exact: true }).click();
    }
    await page.getByRole('button', { name: '返回市场看板（Back to market dashboard）', exact: true }).click();
  }
  await page.getByTestId('sidebar').getByRole('button', { name: '指数（Indices）', exact: true }).click();
  await page.getByLabel('开始日期（Start date）', { exact: true }).fill('2099-01-01');
  await page.getByLabel('结束日期（End date）', { exact: true }).fill('2099-01-02');
  await page.getByText(/^所选范围暂无可用历史/).waitFor();
  await page.getByLabel('结束日期（End date）', { exact: true }).fill('2098-01-01');
  await page.getByRole('alert').getByText(/^请输入有效日期/).waitFor();
  await page.getByRole('button', { name: '返回市场看板（Back to market dashboard）', exact: true }).click();
  steps.push('三市场指数卡打开独立指数页，切换及日期筛选正常，不修改自选，分时缺失明确提示');
  await page.getByTestId('new-session-fab').click();
  assert.equal(await page.locator('.felix-sidebar-new-analysis').count(), 0);
  for (const [code, label] of [['CN', 'A 股（CN）'], ['HK', '港股（HK）'], ['US', '美股（US）']]) {
    await page.getByRole('tab', { name: label, exact: true }).click();
    await page.locator(`[data-testid=market-dashboard][data-market=${code}]`).waitFor();
    await waitForState(page, () => document.querySelector('.felix-index-card .felix-quote-status')?.getAttribute('data-state') !== 'loading');
    await page.screenshot({ path: resolve(artifacts, `market-dashboard-${code}.png`) });
  }
  await page.getByRole('button', { name: '个人概览（Personal overview）', exact: true }).click();
  await page.getByRole('button', { name: '返回市场看板（Back to market dashboard）', exact: true }).click();
  const fab = page.getByTestId('new-session-fab');
  const beforeDrag = await fab.boundingBox();
  await page.mouse.move(beforeDrag.x + 28, beforeDrag.y + 28);
  await page.mouse.down();
  await page.mouse.move(beforeDrag.x - 70, beforeDrag.y - 40, { steps: 8 });
  await page.mouse.up();
  assert.ok((await fab.boundingBox()).x < beforeDrag.x - 50);
  assert.equal(await page.evaluate(async () => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"kernel.hydrate"}' })).json()).data.sessions.length), 0, 'dragging does not create a session');
  steps.push('三市场看板、个人概览入口、可拖动悬浮新会话按钮正常，拖动不会误建会话');
  steps.push('普通浏览器启动，明确标注示例行情与规则分析');
  await fab.click();
  await page.getByTestId('agent-suggestions').waitFor();
  assert.equal(await page.locator('.felix-assistant-questions button').count(), 17);
  await page.getByTestId('assistant-group-stocks').getByRole('button', { name: /^我的自选表现如何/ }).click();
  assert.match(await page.getByTestId('agent-input').inputValue(), /AAPL.US/);
  assert.equal(await page.evaluate(async () => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"kernel.hydrate"}' })).json()).data.sessions.length), 0, 'suggestions only draft, never call the model or create sessions');
  await page.getByTestId('assistant-new-session').click();
  await page.getByTestId('assistant-group-stocks').getByRole('button', { name: /^分析当前个股/ }).click();
  assert.match(await page.getByTestId('agent-input').inputValue(), /还没有指定标的/);
  await page.getByTestId('assistant-expand').click();
  await page.locator('.felix-assistant-expanded').waitFor();
  await page.screenshot({ path: resolve(artifacts, 'assistant-welcome-light.png') });
  await page.getByTestId('assistant-expand').click();
  await page.getByTestId('assistant-close').click();
  await page.getByTestId('agent-panel').waitFor({ state: 'hidden' });
  await fab.click();
  steps.push('AI 助手提供四组17个可编辑问题，打开及点选不建空会话；展开、关闭、再次打开正常');
  await page.getByTestId('agent-input').fill('查询 AAPL.US 的行情');
  await page.getByTestId('agent-input').press('Enter');
  await waitForState(page, async () => {
    const rpc = async (method, args = []) => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ method, args }) })).json()).data;
    const sessions = (await rpc('kernel.hydrate')).sessions;
    return sessions.length && (await rpc('kernel.getMessages', [sessions[0].id])).length === 2;
  });
  await page.getByTestId('agent-input').fill('再次查询 MSFT.US');
  await page.getByTestId('agent-input').press('Enter');
  await waitForState(page, async () => {
    const rpc = async (method, args = []) => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ method, args }) })).json()).data;
    const sessions = (await rpc('kernel.hydrate')).sessions;
    return (await rpc('kernel.getMessages', [sessions[0].id])).length === 4;
  });
  steps.push('从界面连续发送两轮问题，SSE 回答并保存四条消息');
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.getByTestId('agent-panel').waitFor();
  await page.getByTestId('agent-panel').getByText('再次查询 MSFT.US', { exact: true }).waitFor();
  steps.push('刷新后恢复会话与消息');
  await page.getByTestId('sidebar').getByRole('button', { name: /^自选（/ }).click();
  await page.getByTestId('workspace-home').waitFor();
  assert.equal(await page.locator('.felix-sidebar-context').count(), 0, 'lists have moved out of the sidebar');
  const search = page.getByRole('textbox', { name: /^搜索代码或名称/ });
  await search.fill('TSLA');
  await page.getByTestId('watchlist-row-TSLA.US').waitFor({ state: 'visible' });
  assert.equal(await page.getByTestId('watchlist-row-AAPL.US').isVisible(), false);
  await search.fill('');
  await page.getByRole('tab', { name: '港股（HK）', exact: true }).click();
  await page.getByText(/^没有匹配的记录/).waitFor();
  await page.getByRole('tab', { name: '全部市场（All markets）', exact: true }).click();
  await page.getByRole('combobox', { name: /^排列方式/ }).selectOption('symbol');
  await page.getByRole('button', { name: '卡片视图（Card view）', exact: true }).click();
  await page.locator('.felix-watchlist[data-view=cards]').waitFor();
  await page.getByRole('button', { name: '表格视图（Table view）', exact: true }).click();
  assert.deepEqual(await page.locator('.felix-watchlist-open:visible').evaluateAll((buttons) => buttons.map((button) => button.getAttribute('aria-label'))), ['AAPL.US', 'NVDA.US', 'TSLA.US']);
  assert.ok((await page.getByTestId('watchlist-row-AAPL.US').boundingBox()).height >= 42, 'watchlist rows have room for name and quote');
  await page.getByRole('button', { name: '管理分组（Manage groups）', exact: true }).click();
  let groupDialog = page.getByRole('dialog', { name: '管理分组（Manage groups）', exact: true });
  await groupDialog.getByRole('textbox', { name: '分组名称（Group name）', exact: true }).fill('长期关注');
  await groupDialog.getByRole('button', { name: '新建分组（Create group）', exact: true }).click();
  await groupDialog.getByRole('button', { name: '完成（Done）', exact: true }).click();
  await page.getByRole('button', { name: '设置 AAPL.US 的分组（Set groups for AAPL.US）', exact: true }).click();
  groupDialog = page.getByRole('dialog', { name: /所属分组/ });
  await groupDialog.getByRole('checkbox', { name: '长期关注', exact: true }).check();
  await groupDialog.getByRole('button', { name: '完成（Done）', exact: true }).click();
  const groupFilters = page.getByRole('group', { name: '自选分组（Watchlist groups）', exact: true });
  await groupFilters.getByRole('button', { name: /^长期关注/ }).click();
  assert.equal(await page.getByTestId('watchlist-row-TSLA.US').isVisible(), false);
  await page.getByRole('button', { name: '批量导入（Batch import）', exact: true }).click();
  let importDialog = page.getByRole('dialog', { name: '批量导入（Batch import）', exact: true });
  await importDialog.getByRole('textbox', { name: '待导入代码（Codes to import）', exact: true }).fill('MSFT.US, NVDA.US, MSFT.US, BAD');
  assert.equal(await importDialog.locator('[data-state=new]').count(), 1);
  assert.equal(await importDialog.locator('[data-state=duplicate]').count(), 1);
  assert.equal(await importDialog.locator('[data-state=existing]').count(), 1);
  assert.equal(await importDialog.locator('[data-state=invalid]').count(), 1);
  await importDialog.getByRole('button', { name: '取消（Cancel）', exact: true }).click();
  assert.equal(await page.getByTestId('watchlist-row-MSFT.US').count(), 0, 'preview cancellation does not add anything');
  await page.getByRole('button', { name: '批量导入（Batch import）', exact: true }).click();
  importDialog = page.getByRole('dialog', { name: '批量导入（Batch import）', exact: true });
  await importDialog.getByRole('textbox', { name: '待导入代码（Codes to import）', exact: true }).fill('MSFT.US, NVDA.US, MSFT.US, BAD');
  await importDialog.getByRole('button', { name: '确认导入 1 个（Import 1 symbols）', exact: true }).click();
  await page.getByTestId('watchlist-row-MSFT.US').waitFor({ state: 'visible' });
  await waitForState(page, async () => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"workspace.get"}' })).json()).data.groups?.[0].symbols.includes('MSFT.US'));
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.getByTestId('sidebar').getByRole('button', { name: /^自选（/ }).click();
  await page.getByTestId('workspace-home').waitFor();
  await page.getByRole('group', { name: '自选分组（Watchlist groups）', exact: true }).getByRole('button', { name: /^长期关注/ }).click();
  await page.getByTestId('watchlist-row-MSFT.US').waitFor({ state: 'visible' });
  await page.getByRole('button', { name: '管理分组（Manage groups）', exact: true }).click();
  groupDialog = page.getByRole('dialog', { name: '管理分组（Manage groups）', exact: true });
  await groupDialog.getByRole('button', { name: '删除分组 长期关注（Delete group 长期关注）', exact: true }).click();
  await groupDialog.getByRole('button', { name: '取消（Cancel）', exact: true }).click();
  await groupDialog.getByRole('button', { name: '重命名 长期关注（Rename 长期关注）', exact: true }).click();
  await groupDialog.getByRole('textbox', { name: '分组名称（Group name）', exact: true }).fill('重点关注');
  await groupDialog.getByRole('button', { name: '保存名称（Save name）', exact: true }).click();
  await groupDialog.getByRole('button', { name: '完成（Done）', exact: true }).click();
  await page.getByRole('group', { name: '自选分组（Watchlist groups）', exact: true }).getByRole('button', { name: /^全部自选/ }).click();
  let rejectQuoteRefresh = false;
  const quoteRoute = async (route) => {
    const request = route.request().postDataJSON();
    if (request.method !== 'market.getQuote' || request.args?.[0] !== 'AAPL.US') return route.continue();
    const payload = rejectQuoteRefresh ? { ok: false, error: { code: 'OFFLINE', message: 'Fixture quote service unavailable' } }
      : { ok: true, data: { symbol: 'AAPL.US', lastPrice: 123.45, change: 1, changePercent: 0.82, volume: 1000, timestamp: Math.floor(Date.now() / 1000), open: 122, high: 125, low: 120, prevClose: 122.45, provenance: { providerId: 'fixture', providerName: 'Fixture Provider', fetchedAt: Date.now(), stale: false } } };
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify(payload) });
  };
  await page.route('**/api/rpc', quoteRoute);
  await page.getByRole('button', { name: '刷新行情（Refresh quotes）', exact: true }).click();
  await page.getByTestId('quote-status-AAPL.US').getByText('Fixture Provider', { exact: true }).waitFor();
  rejectQuoteRefresh = true;
  await page.getByRole('button', { name: '刷新行情（Refresh quotes）', exact: true }).click();
  await page.locator('[data-testid="quote-status-AAPL.US"][data-state=refreshFailed]').waitFor();
  assert.match(await page.getByTestId('watchlist-row-AAPL.US').innerText(), /123\.45/);
  await page.unroute('**/api/rpc', quoteRoute);
  await page.getByRole('button', { name: '刷新行情（Refresh quotes）', exact: true }).click();
  await page.locator('[data-testid="quote-status-AAPL.US"][data-state=demo]').waitFor();
  steps.push('自选分组可创建、分配、筛选、重命名和持久化；导入预览去重且取消不写入；失败刷新保留真实报价');
  await page.screenshot({ path: resolve(artifacts, 'workspace-home.png') });
  assert.equal(await page.getByRole('tab', { name: '会话（Sessions）', exact: true }).count(), 0);
  await page.getByTestId('new-session-fab').click();
  await page.getByTestId('assistant-history').click();
  const sessionSearch = page.getByRole('textbox', { name: /^搜索会话标题/ });
  await sessionSearch.fill('no-matching-title');
  await page.getByText(/^没有匹配的记录/).waitFor();
  await sessionSearch.fill('');
  await page.locator('.felix-history-open').click();
  await page.getByTestId('agent-input').waitFor({ state: 'visible' });
  await page.getByTestId('assistant-new-session').click();
  await page.getByTestId('agent-input').fill('查询 NVDA.US 的行情');
  await page.getByTestId('agent-input').press('Enter');
  await waitForState(page, () => !document.querySelector('[data-testid=assistant-history]')?.disabled);
  await page.getByTestId('assistant-history').click();
  assert.equal(await page.locator('.felix-assistant-history-row').count(), 2);
  await page.locator('.felix-history-open').last().click();
  await page.getByTestId('agent-panel').getByText('再次查询 MSFT.US', { exact: true }).waitFor();
  await page.getByTestId('assistant-history').click();
  assert.equal(await page.locator('.felix-assistant-history-row').count(), 2, 'history restoration does not create a conversation');
  await page.screenshot({ path: resolve(artifacts, 'assistant-history.png') });
  await page.locator('.felix-history-delete').first().click();
  let sessionDeletion = page.getByRole('dialog', { name: /^删除会话/ });
  await sessionDeletion.getByRole('button', { name: /^取消（/ }).click();
  assert.equal(await page.locator('.felix-assistant-history-row').count(), 2);
  await page.locator('.felix-history-delete').first().click();
  sessionDeletion = page.getByRole('dialog', { name: /^删除会话/ });
  await sessionDeletion.getByRole('button', { name: /^确认删除（/ }).click();
  await waitForState(page, () => document.querySelectorAll('.felix-assistant-history-row').length === 1);
  await page.getByTestId('assistant-history').click();
  steps.push('自选不再混入会话；悬浮助手历史可搜索、恢复、取消删除与确认删除');
  if (!await page.getByTestId('watchlist-row-AAPL.US').count()) {
    await page.getByRole('button', { name: /^添加标的（/ }).click();
    await page.getByPlaceholder('AAPL.US', { exact: true }).fill('AAPL.US');
    await page.getByRole('button', { name: /^确认添加（/ }).click();
  }
  await page.getByTestId('watchlist-row-AAPL.US').click();
  await page.getByRole('tab', { name: 'K 线（Chart）', exact: true }).click();
  await page.locator('.felix-chart-toolbar').waitFor();
  await page.getByRole('button', { name: '返回工作台（Back to workspace）', exact: true }).click();
  await page.getByTestId('workspace-home').waitFor();
  await page.getByTestId('watchlist-row-AAPL.US').click();
  await page.getByRole('tab', { name: 'K 线（Chart）', exact: true }).click();
  const sidebarWidth = (await page.getByTestId('sidebar').boundingBox()).width;
  const assistantToggle = page.locator('.felix-workspace-topbar').getByRole('button', { name: /^研究助手/ });
  await assistantToggle.click();
  await page.waitForTimeout(150);
  assert.ok(Math.abs((await page.getByTestId('sidebar').boundingBox()).width - sidebarWidth) < 2, 'closing the assistant preserves sidebar width');
  await page.screenshot({ path: resolve(artifacts, 'workbench-light.png') });
  await page.getByRole('button', { name: '切换深色主题（Dark theme）', exact: true }).click();
  await waitForState(page, () => document.documentElement.classList.contains('dark'));
  await page.waitForTimeout(250); // Wait for the shared color transitions before visual capture.
  await page.screenshot({ path: resolve(artifacts, 'workbench-dark.png') });
  await assistantToggle.click();
  await page.getByTestId('assistant-new-session').click();
  await page.getByTestId('assistant-expand').click();
  await page.screenshot({ path: resolve(artifacts, 'assistant-welcome-dark.png') });
  await page.getByTestId('assistant-expand').click();
  await page.getByTestId('assistant-close').click();
  await page.getByRole('button', { name: '切换浅色主题（Light theme）', exact: true }).click();
  await assistantToggle.click();
  await page.getByTestId('agent-panel').waitFor({ state: 'visible' });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'workbench fits the viewport');
  steps.push('中英双语行情页、明暗主题及助手开关正常，侧栏宽度保持不变');
  await page.getByTestId('sidebar').getByRole('button', { name: /^研究（/ }).click();
  await page.getByTestId('research-panel').waitFor();
  await page.getByTestId('research-panel').getByRole('button', { name: '深度研究（Deep Research）', exact: true }).click();
  await page.getByTestId('research-report').waitFor({ timeout: 30000 });
  steps.push('从界面启动研究，生成并显示研究报告');
  await page.getByTestId('export-menu-trigger').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByTestId('export-download-markdown').click();
  const download = await downloadPromise;
  assert.match(download.suggestedFilename(), /research\.md$/);
  steps.push('研究报告可下载为 Markdown');
  await page.getByRole('button', { name: /^保存.*投资/ }).click();
  await page.getByTestId('sidebar').getByRole('button', { name: /^投资逻辑（/ }).click();
  await page.getByTestId('thesis-card').waitFor();
  steps.push('研究报告可保存为投资论点，并在完整投资逻辑页面查看');
  for (const label of ['市场看板', '指数', '机会发现', '自选', '投资组合', '对比', '提醒', '研究', '投资逻辑', '事件', '个人与安全', '设置']) {
    const button = page.getByTestId('sidebar').getByRole('button', { name: new RegExp('^' + label + '（') });
    assert.equal(await button.count(), 1, label + ' navigation preserved');
    await button.click(); await page.waitForTimeout(180);
    assert.equal(await page.locator('body').getByText('Something went wrong', { exact: true }).count(), 0);
  }
  steps.push('桌面 12 个金融导航入口正常，逐页打开无脚本错误');
  await page.getByRole('tab', { name: /^AI 设置（/ }).click();
  await page.screenshot({ path: resolve(artifacts, 'settings-models.png') });
  const credential = page.locator('input[type="password"]').first();
  await waitForState(page, () => document.querySelectorAll('input[type="password"]').length >= 5);
  await credential.pressSequentially('dummy-browser-test-key', { delay: 30 });
  await credential.locator('..').getByRole('button', { name: /^保存（/ }).click();
  await waitForState(page, async () => {
    const response = await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"llm.listCredentials"}' });
    return (await response.json()).data.some((item) => item.configured);
  });
  await page.getByRole('button', { name: /^移除（/ }).first().click();
  await waitForState(page, async () => {
    const response = await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"llm.listCredentials"}' });
    return (await response.json()).data.every((item) => !item.configured);
  });
  steps.push('通过原有模型设置页保存及移除访客自己的密钥');
  await page.getByTestId('sidebar').getByRole('button', { name: /^市场看板（/ }).click();
  await page.screenshot({ path: resolve(artifacts, 'web-desktop.png') });
  const second = await browser.newContext();
  const other = await second.newPage(); await other.goto(origin, { waitUntil: 'domcontentloaded' });
  await other.getByTestId('sidebar').waitFor();
  const sessions = await other.evaluate(async () => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"kernel.hydrate"}' })).json()).data.sessions);
  assert.equal(sessions.length, 0); steps.push('新浏览器访客没有前一访客的会话');
  await second.close();
  await page.getByTestId('sidebar').getByRole('button', { name: /^自选（/ }).click();
  if (!await page.getByTestId('watchlist-row-MSFT.US').count()) {
    await page.getByRole('button', { name: /^添加标的（/ }).click();
    await page.getByPlaceholder('AAPL.US', { exact: true }).fill('MSFT.US');
    await page.getByRole('button', { name: /^确认添加（/ }).click();
  }
  await waitForState(page, async () => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"workspace.get"}' })).json()).data.watchlist.includes('MSFT.US'));
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.getByTestId('sidebar').getByRole('button', { name: /^自选（/ }).click();
  await page.getByTestId('watchlist-row-MSFT.US').waitFor();
  steps.push('通过界面修改自选股，刷新后从服务器恢复');
  const username = 'browser-' + Date.now().toString(36), password = 'dummy-browser-password-2026';
  await page.getByTestId('account-bar').getByRole('button', { name: '注册（Register）', exact: true }).click();
  const register = page.getByRole('dialog', { name: '注册（Register）', exact: true });
  await register.getByLabel('用户名（Username）', { exact: true }).fill(username);
  await register.getByLabel(/^密码，至少/).fill(password);
  await register.getByRole('button', { name: '注册（Register）', exact: true }).click();
  await page.getByTestId('recovery-code').waitFor();
  assert.equal((await page.getByTestId('recovery-code').innerText()).length, 43);
  await Promise.all([page.waitForEvent('load'), page.getByRole('button', { name: /^已保存恢复码/ }).click()]);
  await page.getByTestId('account-bar').getByText(new RegExp(username)).waitFor();
  const accountContext = await browser.newContext();
  const accountPage = await accountContext.newPage();
  await accountPage.goto(origin, { waitUntil: 'domcontentloaded' });
  await accountPage.getByTestId('account-bar').getByRole('button', { name: '登录（Sign in）', exact: true }).click();
  const login = accountPage.getByRole('dialog', { name: '登录（Sign in）', exact: true });
  await login.getByLabel('用户名（Username）', { exact: true }).fill(username);
  await login.getByLabel('密码（Password）', { exact: true }).fill(password);
  await Promise.all([accountPage.waitForEvent('load'), login.getByRole('button', { name: '登录（Sign in）', exact: true }).click()]);
  await accountPage.getByTestId('account-bar').getByText(new RegExp(username)).waitFor();
  const accountSessions = await accountPage.evaluate(async () => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"kernel.hydrate"}' })).json()).data.sessions);
  assert.equal(accountSessions.length, 1);
  await accountPage.getByTestId('sidebar').getByRole('button', { name: /^自选（/ }).click();
  await accountPage.getByTestId('watchlist-row-MSFT.US').waitFor();
  await accountPage.getByRole('group', { name: '自选分组（Watchlist groups）', exact: true }).getByRole('button', { name: /^重点关注/ }).waitFor();
  const workspaceDownload = accountPage.waitForEvent('download');
  await accountPage.getByTestId('account-menu-trigger').click();
  await accountPage.getByRole('menuitem', { name: '导出数据（Export data）', exact: true }).click();
  assert.equal((await workspaceDownload).suggestedFilename(), 'felix-workspace.json');
  await accountPage.getByTestId('account-menu-trigger').click();
  await Promise.all([accountPage.waitForEvent('load'), accountPage.getByRole('menuitem', { name: '退出（Sign out）', exact: true }).click()]);
  await accountPage.getByRole('button', { name: '登录（Sign in）', exact: true }).waitFor();
  const afterLogout = await accountPage.evaluate(async () => (await (await fetch('/api/rpc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{"method":"kernel.hydrate"}' })).json()).data.sessions);
  assert.equal(afterLogout.length, 0);
  await accountContext.close();
  steps.push('界面注册和恢复码、另一浏览器登录恢复记录、自选股、导出及退出隔离均通过');
  await page.getByTestId('sidebar').getByRole('button', { name: /^市场看板（/ }).click();
  await page.screenshot({ path: resolve(artifacts, 'web-account-desktop.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByTestId('sidebar').getByRole('button', { name: /^自选（/ }).click();
  await page.getByTestId('workspace-home').waitFor({ state: 'visible' });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile workspace fits the viewport');
  assert.equal(await page.getByTestId('sidebar').locator('.felix-sidebar-nav-label').first().isVisible(), false, 'narrow navigation shows icons with accessible labels');
  await page.screenshot({ path: resolve(artifacts, 'workspace-mobile.png') });
  await page.getByTestId('sidebar').getByRole('button', { name: /^市场看板（/ }).click();
  await page.getByTestId('market-dashboard').waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile dashboard fits the viewport');
  await page.screenshot({ path: resolve(artifacts, 'market-dashboard-mobile.png') });
  await page.locator('.felix-index-card').first().getByRole('button').click();
  await page.getByTestId('index-workspace').waitFor();
  await page.getByTestId('chart-canvas').waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile index workspace fits the viewport');
  await page.screenshot({ path: resolve(artifacts, 'indices-mobile.png') });
  await page.getByRole('button', { name: '返回市场看板（Back to market dashboard）', exact: true }).click();
  const mobileFab = await page.getByTestId('new-session-fab').boundingBox();
  assert.ok(mobileFab.x >= 0 && mobileFab.x + mobileFab.width <= 390, 'floating button remains reachable after resizing');
  await page.getByTestId('sidebar').getByRole('button', { name: /^自选（/ }).click();
  await page.getByTestId('new-session-fab').click();
  await page.getByTestId('assistant-history').click();
  await page.locator('.felix-history-open').click();
  await page.getByTestId('agent-input').waitFor({ state: 'visible' });
  await page.getByRole('navigation', { name: '视图切换', exact: true }).getByRole('button', { name: '工作台（Workspace）', exact: true }).click();
  await page.getByTestId('new-session-fab').click();
  await page.getByTestId('assistant-history').click();
  await page.locator('.felix-history-open').click();
  await page.getByTestId('agent-input').waitFor({ state: 'visible' });
  await page.screenshot({ path: resolve(artifacts, 'web-mobile.png') });
  await page.getByTestId('assistant-new-session').click();
  await page.getByTestId('assistant-group-stocks').getByRole('button', { name: /^我的自选表现如何/ }).click();
  assert.ok((await page.getByTestId('agent-input').inputValue()).length > 0);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'assistant questions fit narrow screens');
  await page.screenshot({ path: resolve(artifacts, 'assistant-mobile.png') });
  await page.getByTestId('assistant-close').click();
  await page.getByTestId('workspace-home').waitFor();
  steps.push('390px 手机工作台无横向溢出，恢复当前会话也能切换到研究助手');
  await page.getByTestId('account-menu-trigger').click();
  await page.getByRole('menuitem', { name: '删除账号（Delete account）', exact: true }).click();
  const deletion = page.getByRole('dialog', { name: '删除账号和数据（Delete account and data）', exact: true });
  await deletion.getByLabel('密码（Password）', { exact: true }).fill(password);
  await deletion.getByLabel('输入用户名确认（Type username to confirm）', { exact: true }).fill(username);
  await Promise.all([page.waitForEvent('load'), deletion.getByRole('button', { name: '删除账号和数据（Delete account and data）', exact: true }).click()]);
  await page.getByRole('button', { name: '登录（Sign in）', exact: true }).waitFor();
  steps.push('通过界面删除测试账号和服务器工作区');
  assert.deepEqual(errors, []);
  await writeFile(resolve(artifacts, 'browser-result.json'), JSON.stringify({ passed: true, steps, pageErrors: errors }, null, 2));
  console.log(JSON.stringify({ passed: true, steps, pageErrors: errors }, null, 2));
} catch (error) {
  await page?.screenshot({ path: resolve(artifacts, 'web-failure.png') }).catch(() => {});
  console.error(JSON.stringify({ passed: false, steps, pageErrors: errors, error: error.message, requestCounts,
    visibleText: ((await page?.locator('body').innerText().catch(() => '')) ?? '').slice(0, 2200) }, null, 2));
  process.exitCode = 1;
} finally { await browser.close(); }
